wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.1
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1722720269
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 7
      - 8
      - 19
      - 23
      - 38
      4: 3.11.4
      5: 0.17.1
      8:
      - 1
      - 3
      - 5
      10:
      - 9
      13: windows-amd64
    m:
    - 1: epoch/epoch
      6:
      - 3
learning_rate:
  desc: null
  value: 1.0e-05
epochs:
  desc: null
  value: 2
batch_size:
  desc: null
  value: 32
input_shape:
  desc: null
  value:
  - 299
  - 299
  - 3
