wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.5
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1722883815
    t:
      1:
      - 3
      - 55
      2:
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 19
      - 23
      4: 3.10.14
      5: 0.17.5
      8:
      - 1
      - 5
      13: linux-x86_64
learning_rate:
  desc: null
  value: 1.0e-05
epochs:
  desc: null
  value: 15
batch_size:
  desc: null
  value: 32
input_shape:
  desc: null
  value:
  - 299
  - 299
  - 3
